apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: shivam1994/microservice-kubernetes-demo-apache:latest
        ports:
        - containerPort: 80
